id: wp_jamstack_deployments-c5f12e55-3608-415a-82ce-34781994111c

info:
  name: >
    JAMstack Deployments <= 1.1.1 - Missing Authorization
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/c5f12e55-3608-415a-82ce-34781994111c?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/wp-jamstack-deployments/"
    google-query: inurl:"/wp-content/plugins/wp-jamstack-deployments/"
    shodan-query: 'http.html:"wp-content/plugins/wp-jamstack-deployments/"'
  tags: cve,wordpress,wp-plugin,wp-jamstack-deployments,high,candidate

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/wp-jamstack-deployments/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "wp-jamstack-deployments"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.1.1')