id: video_conferencing_with_zoom_api-512e042e-c280-4966-b41c-ce589ca035af

info:
  name: >
    Video Conferencing with Zoom < 4.6.6 - Missing Authorization
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/512e042e-c280-4966-b41c-ce589ca035af?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/video-conferencing-with-zoom-api/"
    google-query: inurl:"/wp-content/plugins/video-conferencing-with-zoom-api/"
    shodan-query: 'http.html:"wp-content/plugins/video-conferencing-with-zoom-api/"'
  tags: cve,wordpress,wp-plugin,video-conferencing-with-zoom-api,high,candidate

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/video-conferencing-with-zoom-api/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "video-conferencing-with-zoom-api"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '< 4.6.6')